project:
  type: website
  output-dir: docs
  title: "John Baker"

title-meta: "John Baker"
description-meta: "The Digital Garden of John Baker"

website:
  search: false
  back-to-top-navigation: true
  navbar:
    pinned: true
    background: primary
    right:
      - text: About
        href: about/index.qmd
      - text: Work
        href: work/index.qmd
      - text: Contact
        href: contact/index.qmd

  repo-url: "https://github.com/baker-jr-john/mywebsite.git"
  repo-actions: none

  page-footer: 
    border: true
    left: Made with {{< fa heart >}} and [![Quarto](https://quarto.org/quarto.png){width=65}](https://quarto.org/){target="_blank"} 
    right: |
      [{{< fa brands github >}}](https://github.com/baker-jr-john/mywebsite.git){target="_blank"}

format:
  html:
    page-layout: full
    sidebar: false
    mainfont: Lato
    respect-user-color-scheme: true
    theme: 
      light: light.scss
      dark: dark.scss
    toc: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/(?:www\.)?johnbaker\.io(?:\/|$)'
